import {
    Heart,
    Star,
    Settings,
    User,
    Home,
    Search,
    Mail,
    Phone,
    Calendar,
    Clock,
    MapPin,
    Download,
    Upload,
    Edit,
    Delete,
    Plus,
    Minus,
    Check,
    X,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    Menu,
    Info,
    AlertCircle,
    CheckCircle,
    XCircle,
    HelpCircle,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    Zap,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    Filter,
    SortAsc,
    SortDesc,
    RefreshCw,
    RotateCcw,
    RotateCw,
    ZoomIn,
    ZoomOut,
    Maximize,
    Minimize,
    ExternalLink,
    Link,
    Copy,
    Share,
    Bookmark,
    Flag,
    ThumbsUp,
    ThumbsDown,
    MessageCircle,
    MessageSquare,
    Bell,
    Shield,
    Award,
    Gift,
    ShoppingCart,
    CreditCard,
    DollarSign,
    Percent,
    TrendingUp,
    TrendingDown,
    Activity,
    BarChart,
    PieChart,
    LineChart,
    Database,
    Server,
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Printer,
    Camera,
    Video,
    Music,
    File,
    Folder,
    Archive,
    Trash2,
    Save,
    DownloadCloud,
    UploadCloud,
    Cloud,
    Wifi,
    Bluetooth,
    Battery,
    Power,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    Mic,
    MicOff,
    Headphones,
    Speaker,
    Radio,
    Tv,
    Gamepad2,
    Mouse,
    Keyboard,
    HardDrive,
    Cpu,
    Thermometer,
    Droplets,
    Sun,
    Moon,
    CloudRain,
    CloudSnow,
    Wind,
    Umbrella,
    Snowflake,
    Flame,
    Sparkles,
    IceCream,
    // Additional useful icons
    HeartOff,
    StarOff,
    Settings2,
    Users,
    Building,
    Map,
    Navigation,
    Globe,
    MailOpen,
    PhoneCall,
    PhoneIncoming,
    PhoneOutgoing,
    CalendarDays,
    CalendarRange,
    Clock1,
    Clock2,
    Clock3,
    Clock4,
    Clock5,
    Clock6,
    Clock7,
    Clock8,
    Clock9,
    Clock10,
    Clock11,
    Clock12,
    MapPinOff,
    Navigation2,
    NavigationOff,
    Edit2,
    Edit3,
    Trash,
    PlusCircle,
    MinusCircle,
    XSquare,
    AlertTriangle,
    AlertOctagon,
    Grid,
    Layout,
    Image,} from 'lucide-vue-next'
// Icon mapping object with useful icons
export const iconMap = {
    // Basic icons
    'heart': Heart,
    'star': Star,
    'settings': Settings,
    'user': User,
    'home': Home,
    'search': Search,
    'mail': Mail,
    'phone': Phone,
    'calendar': Calendar,
    'clock': Clock,
    'map-pin': MapPin,
    'download': Download,
    'upload': Upload,
    'edit': Edit,
    'delete': Delete,
    'plus': Plus,
    'minus': Minus,
    'check': Check,
    'x': X,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'menu': Menu,
    'close': X,
    'info': Info,
    'alert-circle': AlertCircle,
    'check-circle': CheckCircle,
    'x-circle': XCircle,
    'help-circle': HelpCircle,
    'eye': Eye,
    'eye-off': EyeOff,
    'lock': Lock,
    'unlock': Unlock,
    'zap': Zap,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'filter': Filter,
    'sort-asc': SortAsc,
    'sort-desc': SortDesc,
    'refresh-cw': RefreshCw,
    'rotate-ccw': RotateCcw,
    'rotate-cw': RotateCw,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut,
    'maximize': Maximize,
    'minimize': Minimize,
    'external-link': ExternalLink,
    'link': Link,
    'copy': Copy,
    'share': Share,
    'bookmark': Bookmark,
    'flag': Flag,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
    'message-circle': MessageCircle,
    'message-square': MessageSquare,
    'bell': Bell,
    'shield': Shield,
    'award': Award,
    'gift': Gift,
    'shopping-cart': ShoppingCart,
    'credit-card': CreditCard,
    'dollar-sign': DollarSign,
    'percent': Percent,
    'trending-up': TrendingUp,
    'trending-down': TrendingDown,
    'activity': Activity,
    'bar-chart': BarChart,
    'pie-chart': PieChart,
    'line-chart': LineChart,
    'database': Database,
    'server': Server,
    'monitor': Monitor,
    'smartphone': Smartphone,
    'tablet': Tablet,
    'laptop': Laptop,
    'printer': Printer,
    'camera': Camera,
    'video': Video,
    'music': Music,
    'file': File,
    'folder': Folder,
    'archive': Archive,
    'trash-2': Trash2,
    'save': Save,
    'download-cloud': DownloadCloud,
    'upload-cloud': UploadCloud,
    'cloud': Cloud,
    'wifi': Wifi,
    'bluetooth': Bluetooth,
    'battery': Battery,
    'power': Power,
    'volume': Volume,
    'volume1': Volume1,
    'volume2': Volume2,
    'volume-x': VolumeX,
    'mic': Mic,
    'mic-off': MicOff,
    'headphones': Headphones,
    'speaker': Speaker,
    'radio': Radio,
    'tv': Tv,
    'gamepad-2': Gamepad2,
    'mouse': Mouse,
    'keyboard': Keyboard,
    'hard-drive': HardDrive,
    'cpu': Cpu,
    'thermometer': Thermometer,
    'droplets': Droplets,
    'sun': Sun,
    'moon': Moon,
    'cloud-rain': CloudRain,
    'cloud-snow': CloudSnow,
    'wind': Wind,
    'umbrella': Umbrella,
    'snowflake': Snowflake,
    'flame': Flame,
    'sparkles': Sparkles,
    'ice-cream': IceCream,
    // Additional useful icons
    'heart-off': HeartOff,
    'star-off': StarOff,
    'settings-2': Settings2,
    'users': Users,
    'building': Building,
    'map': Map,
    'navigation': Navigation,
    'globe': Globe,
    'mail-open': MailOpen,
    'phone-call': PhoneCall,
    'phone-incoming': PhoneIncoming,
    'phone-outgoing': PhoneOutgoing,
    'calendar-days': CalendarDays,
    'calendar-range': CalendarRange,
    'clock-1': Clock1,
    'clock-2': Clock2,
    'clock-3': Clock3,
    'clock-4': Clock4,
    'clock-5': Clock5,
    'clock-6': Clock6,
    'clock-7': Clock7,
    'clock-8': Clock8,
    'clock-9': Clock9,
    'clock-10': Clock10,
    'clock-11': Clock11,
    'clock-12': Clock12,
    'map-pin-off': MapPinOff,
    'navigation-2': Navigation2,
    'navigation-off': NavigationOff,
    'edit-2': Edit2,
    'edit-3': Edit3,
    'trash': Trash,
    'plus-circle': PlusCircle,
    'minus-circle': MinusCircle,
    'x-square': XSquare,
    'alert-triangle': AlertTriangle,
    'alert-octagon': AlertOctagon,
    'layout': Layout,
    'image': Image,    'grid': Grid,
} as const

export const sizeMap = {
    'xs': 16,
    'sm': 20,
    'md': 24,
    'lg': 32,
    'xl': 40,
    '2xl': 48,
} as const

export const inputTypesMap = [
    'button',
    'checkbox',
    'color',
    'date',
    'datetime-local',
    'email',
    'file',
    'hidden',
    'image',
    'month',
    'number',
    'password',
    'radio',
    'range',
    'reset',
    'search',
    'submit',
    'tel',
    'text',
    'time',
    'url',
    'week',
] as const

export const variantMap = [
    'bordered',
    'ghost',
    'primary',
    'secondary',
    'accent',
    'info',
    'success',
    'warning',
    'error',
    'link',    'neutral',
] as const
