name: Testing Suite

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

env:
    NODE_VERSION: '22.20.0'

jobs:
    # Unit Tests
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.20.0] # only 22 is supported for now

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install --prefer-online

            - name: Run unit tests
              run: npm run test

    #          run: npm run test:coverage
    #
    #        - name: Upload coverage
    #          uses: codecov/codecov-action@v4
    #         with:
    #             file: coverage/lcov.info 
    #             flags: unittests
    #             name: codecov-umbrella
    #          continue-on-error: true

    # Integration Tests
    integration-tests:
        name: Integration Tests
        runs-on: ubuntu-latest
        needs: unit-tests

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install --prefer-online

            - name: Prepare playground
              run: npm run dev:prepare

            - name: Build playground
              run: cd playground && npm run build

            # - name: Test playground build
            #  run: cd playground && npm run test:types

    # Component Testing
    component-tests:
        name: Component Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install --prefer-online

            - name: Run Storybook build test
              run: npm run storybook:build
              continue-on-error: true

            - name: Upload Storybook build
              uses: actions/upload-artifact@v4
              with:
                  name: storybook-build
                  path: storybook-static/
                  retention-days: 7

    # Performance Tests
    performance-tests:
        name: Performance Tests
        runs-on: ubuntu-latest
        needs: integration-tests

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install --prefer-online

            - name: Build for performance testing
              run: npm run prepack

            - name: Run Lighthouse CI
              run: |
                  # Install Lighthouse CI
                  npm install -g @lhci/cli@0.12.x

                  # Run Lighthouse on playground
                  cd playground
                  npm run generate

                  # Basic performance check
                  echo "Performance test completed"
              continue-on-error: true
